# Generated by Django 3.2.2 on 2021-07-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
                ('uploadImg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.uploadimg')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.author')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.comment')),
            ],
        ),
    ]
