# Generated by Django 3.2.6 on 2021-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='UploadImg',
            field=models.ManyToManyField(blank=True, to='gallery.UploadImg'),
        ),
    ]
