# Generated by Django 3.2.6 on 2021-10-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_contactme'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_img',
            field=models.ImageField(null=True, upload_to='category-img'),
        ),
    ]
