# Generated by Django 3.2.6 on 2021-11-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_category_cate_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uploadImg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.uploadimg'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.author'),
        ),
    ]
