# Generated by Django 3.2.6 on 2021-11-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20211115_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='authors',
            field=models.ManyToManyField(blank=True, to='gallery.Author'),
        ),
    ]
