# Generated by Django 3.2.6 on 2022-01-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='razorpay_orderId',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='donate',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='payment_status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
