# Generated by Django 3.2.6 on 2022-01-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20220114_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
