# Generated by Django 3.2.6 on 2022-01-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_donate_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='payment_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
